### ISSUE TITLE
Code is not updated on galaxy

### ISSUE THREAD

**Issue by krahser** [gorsuch/ansible-docker-role#9]
Hi,

The code is not updated in galaxy. If you look [here](https://github.com/gorsuch/ansible-docker-role/blob/master/tasks/main.yml). The task 'docker.io apt key' is commented, but I got this error from running the role.

![ssl-error](https://user-images.githubusercontent.com/232739/35956135-5ce797bc-0cc6-11e8-8208-3f2bd4f6eca7.png)

Thanks in advance

**Comment by krahser** [comment]
Hi @gorsuch, could you import again on galaxy, please?

**Comment by gorsuch** [comment]
done! can you confirm that things are up to date?

**Comment by krahser** [comment]
No, it doesn't I update the role version on meta/main.yml on the new pull request.
I notice that the version that ansible galaxy is reporting is v0.3.0, and I guess that it comes from the tag on the repo. maybe we should create the tag v0.3.1? btw, I also update the name of the docker package, since now they use docker-ce.

**Comment by krahser** [comment]
@gorsuch I've updated the repo url and key to match with [docker installation doc](https://docs.docker.com/install/linux/docker-ce/ubuntu/#set-up-the-repository).

could you please take a look at the pull request and update the tag to see if that updates galaxy?
Thanks in advance.

**Comment by gorsuch** [comment]
I just re-imported on galaxy.  I will work on testing ASAP.  Let me know if you have a chance to test it first.

Also, we should discuss transferring this repo over to you -- I don't use this project any longer and am not doing my part as a good maintainer.  Let me know if you are interested, and I can get out of your way!

**Comment by krahser** [comment]
Ok, let's transfer it. Thanks.

**Comment by gorsuch** [comment]
I just added you as a collaborator to this repo.

If you'd like, I can push up a README update that states that your fork is now the canonical version.  Also happy to accept any other suggestions for the transfer.

**Comment by krahser** [comment]
It's OK, I could work on your repo, if that's OK for you.

**Comment by gorsuch** [comment]
That's fine by me!
